import { NginxConfig } from '@/types/nginx';

export const generateDockerfile = (config: NginxConfig): string => {
  // Collect all unique ports from servers
  const ports = new Set<string>();
  config.servers.forEach(server => {
    ports.add(String(server.listen.port));
    // If SSL is enabled with force redirect, also expose port 80
    if (server.ssl.enabled && server.ssl.forceRedirect) {
      ports.add('80');
    }
  });
  config.stream.servers.forEach((server) => {
    ports.add(server.udp ? `${server.listenPort}/udp` : String(server.listenPort));
  });
  
  // Default to port 80 if no servers configured
  if (ports.size === 0) {
    ports.add('80');
  }
  
  const exposeLines = Array.from(ports)
    .sort((left, right) => Number.parseInt(left, 10) - Number.parseInt(right, 10))
    .map(port => `EXPOSE ${port}`)
    .join('\n');
  
  return `# Generated by Nginx Config Master
# https://nginx-config-master.lovable.app

# Based on lightweight Nginx Alpine image
FROM nginx:alpine

# Remove default configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy generated configuration file
# Make sure nginx.conf is in the same directory as this Dockerfile
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports
${exposeLines}

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
`;
};
