import { describe, expect, it } from 'vitest';
import { parseNginxConfig } from '@/utils/nginxParser';
import { prepareImportedNginxSource } from '@/utils/sourceTools';

const imported = `# 原始注释
http {
 server {
listen 80;
server_name demo.test;
location ~ ^/[^/]+\\.txt$ {
try_files $uri =404; # 行尾注释
add_header X-Keep "unchanged";
}
 }
}

stream {
upstream socket_proxy {
hash $remote_addr consistent;
server 172.16.0.16:15676 weight=5 max_fails=3 fail_timeout=30s;
}
}
`;

const meaningfulLines = (source: string) => source
  .split(/\r?\n/)
  .map((line) => line.trim())
  .filter(Boolean);

describe('import source preparation', () => {
  it('changes indentation only and preserves every directive and comment', () => {
    const formatted = prepareImportedNginxSource(imported);

    expect(meaningfulLines(formatted)).toEqual(meaningfulLines(imported));
    expect(formatted).toContain('# 原始注释');
    expect(formatted).toContain('location ~ ^/[^/]+\\.txt$ {');
    expect(formatted).toContain('try_files $uri =404; # 行尾注释');
    expect(formatted).toContain('hash $remote_addr consistent;');
    expect(formatted).not.toContain('Generated by');
    expect(formatted).not.toContain('/usr/share/nginx/modules/*.conf');
    expect(parseNginxConfig(formatted).rawConfig).toBe(formatted);
  });
});
