import { describe, expect, it } from 'vitest';
import { parseNginxConfig } from '@/utils/nginxParser';
import { generateNginxConfig } from '@/utils/configGenerator';
import { mergeNginxConfigSource } from '@/utils/sourceMerge';
import {
  createDefaultStreamServer,
  createDefaultStreamUpstream,
  defaultNginxConfig,
} from '@/types/nginx';

const importedSource = `# 原文件头注释
worker_processes auto;

events {
    worker_connections 2048;
}

http {
    # 正则 location 必须保留
    server {
        listen 80;
        server_name demo.test;

        location ~ ^/[^/]+\\.txt$ {
            root /www/webapp;
            try_files $uri =404;
            add_header X-Custom "keep-me";
        }
    }
}

stream {
    # Socket 配置不属于 nginx-flow 表单，但必须原样保留
    upstream socket_proxy {
        hash $remote_addr consistent;
        server 172.16.0.16:15676 weight=5 max_fails=3 fail_timeout=30s;
    }
    server {
        listen 15675;
        proxy_pass socket_proxy;
    }
}
`;

describe('lossless imported source', () => {
  it('returns imported source byte-for-byte before any edit', () => {
    const config = parseNginxConfig(importedSource);
    expect(generateNginxConfig(config)).toBe(importedSource);
  });

  it('patches a visual field without removing comments or stream blocks', () => {
    const before = parseNginxConfig(importedSource);
    const location = before.locations[0];
    const after = structuredClone(before);
    after.locations[0] = { ...location, tryFiles: '$uri $uri/ =404' };
    const merged = mergeNginxConfigSource(importedSource, before, after);

    expect(merged).toContain('try_files $uri $uri/ =404;');
    expect(merged).toContain('# 正则 location 必须保留');
    expect(merged).toContain('# Socket 配置不属于 nginx-flow 表单，但必须原样保留');
    expect(merged).toContain('hash $remote_addr consistent;');
    expect(merged).toContain('add_header X-Custom "keep-me";');
  });

  it('patches a global value without adding pid, user or generated headers', () => {
    const before = parseNginxConfig(importedSource);
    const after = structuredClone(before);
    after.global.workerProcesses = '4';
    const merged = mergeNginxConfigSource(importedSource, before, after);

    expect(merged).toContain('worker_processes 4;');
    expect(merged).not.toContain('pid /run/nginx.pid;');
    expect(merged).not.toContain('Generated by');
  });

  it('parses Stream upstreams and TCP listeners into the visual model', () => {
    const config = parseNginxConfig(importedSource);

    expect(config.stream.upstreams).toHaveLength(1);
    expect(config.stream.upstreams[0]).toMatchObject({
      name: 'socket_proxy',
      hashKey: '$remote_addr',
      hashConsistent: true,
    });
    expect(config.stream.upstreams[0].servers[0]).toMatchObject({
      address: '172.16.0.16',
      port: 15676,
      weight: 5,
      maxFails: 3,
      failTimeout: 30,
    });
    expect(config.stream.servers[0]).toMatchObject({
      listenPort: 15675,
      proxyPass: 'socket_proxy',
    });
  });

  it('merges Stream edits without deleting the original comments', () => {
    const before = parseNginxConfig(importedSource);
    const after = structuredClone(before);
    after.stream.upstreams[0].name = 'socket_cluster';
    after.stream.upstreams[0].servers[0].weight = 8;
    after.stream.servers[0].listenPort = 16675;
    after.stream.servers[0].proxyPass = 'socket_cluster';
    after.stream.servers[0].socketKeepalive = true;

    const merged = mergeNginxConfigSource(importedSource, before, after);

    expect(merged).toContain('upstream socket_cluster {');
    expect(merged).toContain('server 172.16.0.16:15676 weight=8;');
    expect(merged).toContain('listen 16675;');
    expect(merged).toContain('proxy_socket_keepalive on;');
    expect(merged).toContain('proxy_pass socket_cluster;');
    expect(merged).toContain('# Socket 配置不属于 nginx-flow 表单，但必须原样保留');
  });

  it('appends a new Stream block without rebuilding an imported HTTP config', () => {
    const source = importedSource.slice(0, importedSource.indexOf('\nstream {')).trimEnd() + '\n';
    const before = parseNginxConfig(source);
    const after = structuredClone(before);
    const upstream = createDefaultStreamUpstream();
    const server = createDefaultStreamServer(upstream.name);
    after.stream = { upstreams: [upstream], servers: [server], customDirectives: '' };

    const merged = mergeNginxConfigSource(source, before, after);

    expect(merged).toContain('# 原文件头注释');
    expect(merged).toContain('stream {');
    expect(merged).toContain(`upstream ${upstream.name} {`);
    expect(merged).toContain(`proxy_pass ${upstream.name};`);
    expect(merged).not.toContain('Generated by');
  });
});

describe('new config defaults', () => {
  it('includes the standard dynamic module directory by default', async () => {
    const generated = generateNginxConfig(structuredClone(defaultNginxConfig));

    expect(generated).toContain('include /usr/share/nginx/modules/*.conf;');
  });

  it('generates a deployable Stream block for a new visual config', () => {
    const config = structuredClone(defaultNginxConfig);
    const upstream = createDefaultStreamUpstream();
    upstream.name = 'socket_proxy';
    upstream.hashKey = '$remote_addr';
    upstream.hashConsistent = true;
    upstream.servers[0] = {
      ...upstream.servers[0],
      address: '172.16.0.16',
      port: 15676,
      weight: 5,
    };
    const server = createDefaultStreamServer(upstream.name);
    server.listenPort = 15675;
    config.stream = { upstreams: [upstream], servers: [server], customDirectives: '' };

    const generated = generateNginxConfig(config);

    expect(generated).toContain('stream {');
    expect(generated).toContain('hash $remote_addr consistent;');
    expect(generated).toContain('server 172.16.0.16:15676 weight=5;');
    expect(generated).toContain('listen 15675;');
    expect(generated).toContain('proxy_pass socket_proxy;');
  });

  it('does not inject the default include into an imported file', () => {
    const config = parseNginxConfig(importedSource);
    expect(generateNginxConfig(config)).not.toContain('/usr/share/nginx/modules/*.conf');
  });
});
